#
# Module manifest for module 'Universal'
#
# Generated by: Adam Driscoll
#
# Generated on: 5/16/2020
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule         = 'Universal.psm1'
    
    # Version number of this module.
    ModuleVersion = '2.12.2'
    
    # Supported PSEditions
    # CompatiblePSEditions = @()
    
    # ID used to uniquely identify this module
    GUID               = '8fd8507b-4df7-477f-854e-f31e8a0fa830'
    
    # Author of this module
    Author             = 'Ironman Software'
    
    # Company or vendor of this module
    CompanyName        = 'Ironman Software'
    
    # Copyright statement for this module
    Copyright          = '(c) 2022 Ironman Software. All rights reserved.'
    
    # Description of the functionality provided by this module
    Description        = 'Module for PowerShell Universal.'
    
    # Minimum version of the Windows PowerShell engine required by this module
    # PowerShellVersion = ''
    
    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''
    
    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''
    
    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''
    
    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''
    
    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''
    
    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()
    
    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @('UniversalDashboard.Common.dll', 'UniversalDashboard.dll')
    
    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()
    
    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()
    
    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()
    
    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules      = @('UniversalDashboard.dll', 'Universal.Cmdlets.dll')

    AliasesToExport    = @(
        'Add-PSUScriptTag'
        'Connect-UAServer'
        'Get-PSUComputer'
        'Get-PSUDashboardFramework'
        'Get-PSUFolder'
        'Get-PSUGitStatus'
        'Get-PSUIdentity'
        'Get-PSUJob'
        'Get-PSUJobFeedback'
        'Get-PSUJobOutput'
        'Get-PSUJobParameter'
        'Get-PSUJobPipelineOutput'
        'Get-PSURole'
        'Get-PSUSchedule'
        'Get-PSUScript'
        'Get-PSUScriptHistory'
        'Get-PSUScriptParameter'
        'Get-PSUScriptTag'
        'Get-PSUSetting'
        'Get-PSUStats'
        'Get-PSUTag'
        'Get-PSUVariable'    
        'Get-UAAppToken'
        'Get-UDDashboard'
        'Grant-UAAppToken'
        'Invoke-PSUScript'
        'Add-UDDashboard'
        'New-PSUDashboardComponent'
        'New-PSUDashboardFramework'
        'New-PSUIdentity'
        'New-PSUTag'
        'New-PSUFolder'
        'New-PSUPowerShellVersion'
        'New-PSUSchedule'
        'New-PSUVariable'
        'New-UAScript'
        'Measure-UDBlock'
        'Out-PSUPipeline'
        'Remove-PSUIdentity'
        'Remove-PSUSchedule'
        'Remove-PSUScript'
        'Remove-PSUScriptTag'
        'Remove-PSUTag'
        'Remove-PSUVariable'
        'Rename-PSUScript'
        'Revoke-PSUAppToken'
        'Set-PSUIdentity'
        'Set-PSUJobFeedback'
        'Set-PSUScript'
        'Set-PSUTag'
        'Set-PSUVariable'
        'Set-PSULicense'
        'Set-PSUSetting'
        'Start-PSUDashboard'
        'Stop-PSUDashboard'
        'Stop-PSUJob'
        'Stop-PSUServer'
        'Wait-PSUJob'
    )
    FunctionsToExport  = @(
        'Install-PSUServer'
        'Resolve-Variable'
        'Start-PSUServer',
        'Update-PSUServer',
        'Remove-PSUServer'
    )
    CmdletsToExport    = @(
        'Add-UAScriptTag'
        'New-PSUDashboard'
        'Add-UDDashboardComponent'
        'Add-UDDashboardFramework'
        'Clear-UDCache'
        'ConvertTo-JsonEx'
        'Get-PSUDashboardEndpointRunspace'
        'Connect-PSUServer'
        'ConvertTo-JsonEx'
        'Get-PSUEndpoint'
        'Get-PSUAppToken'
        'Get-UAComputer'
        'Get-UAFolder'
        'Get-UAGitStatus'
        'Get-UAIdentity'
        'Get-UAJob'
        'Get-UAJobFeedback'
        'Get-UAJobOutput'
        'Get-UAJobParameter'
        'Get-UAJobPipelineOutput'
        'Get-UALicense'
        'Get-UAPowerShellVersion'
        'Get-UARole'
        'Get-UASchedule'
        'Get-UAScript'
        'Get-UAScriptHistory'
        'Get-UAScriptParameter'
        'Get-UAScriptTag'
        'Get-UASetting'
        'Get-UAStats'
        'Get-UATag'
        'Get-UAVariable'
        'Get-PSUTerminal'
        'Get-PSUDashboard'
        'Get-UDDashboardFramework'
        'Get-PSUTerminalInstance'
        'Grant-PSUAppToken'
        'Invoke-UAScript'
        'Invoke-UDEndpoint'
        'Invoke-PSUTerminalCommand'
        'Import-PSUTemplate'
        'New-PSUApiResponse'
        'New-PSUAuthenticationResult'
        'New-PSUAuthorizationClaim'
        'New-PSUEnvironment'
        'Get-PSUEnvironment'
        'New-PSUEndpoint'
        'New-PSUHotkey'
        'New-PSURole'
        'New-PSUScript'
        'New-PSUTerminal'
        'Start-PSUTerminalInstance'
        'Stop-PSUTerminalInstance'
        'New-UAFolder'
        'New-UAIdentity'
        'New-PSUPage'
        'New-UAPowerShellVersion'
        'New-UASchedule'
        'New-UATag'
        'New-UAVariable'
        'New-UDElement'
        'New-UDEndpoint'
        'New-UDEndpointSchedule'
        'New-UDHtml'
        'New-PSUPublishedFolder'
        'New-PSURateLimit'
        'New-PSUValidationResult'
        'Measure-PSUBlock'
        'Out-UAPipeline'
        'Remove-PSUEndpoint'
        'Remove-UAIdentity'
        'Remove-PSUEnvironment'
        'Remove-UASchedule'
        'Remove-UAScript'
        'Remove-UAScriptTag'
        'Remove-UATag'
        'Remove-UAVariable'
        'Remove-UDEndpoint'
        'Rename-UAScript'
        'Revoke-UAAppToken'
        'Set-PSUAuthenticationMethod'
        'Set-UAIdentity'
        'Set-UAJobFeedback'
        'Set-UALicense'
        'Set-UAPowerShellVersion'
        'Set-UAScript'
        'Set-UASetting'
        'Set-UATag'
        'Set-UAVariable'
        'Start-UDDashboard'
        'Stop-UAJob'
        'Stop-UAServer'
        'Stop-UDDashboard'
        'Sync-PSUComponent'
        'Sync-PSUConfiguration'
        'Wait-UAJob'
        'Wait-PSUDashboardEndpoint'
        'New-PSUTrigger'
        'Set-PSUTrigger'
        'Get-PSUTrigger'
        'Remove-PSUTrigger'
        'New-PSULoginPage'
        'Set-PSUCache'
        'Get-PSUCache'
        'New-PSUAccessControl'
        'New-PSULoginPageLink'
    )
    
    VariablesToExport  = ''
    # DSC resources to export from this module
    # DscResourcesToExport = @()
    
    # List of all modules packaged with this module
    # ModuleList = @()
    
    # List of all files packaged with this module
    # FileList = @()
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData        = @{
    
        PSData = @{
    
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('universal', 'universal-dashboard', 'universal-automation')
    
            # A URL to the license for this module.
            LicenseUri   = 'https://ironmansoftware.com/legal/'
    
            # A URL to the main website for this project.
            ProjectUri   = 'https://ironmansoftware.com/powershell-universal'
    
            # A URL to an icon representing this module.
            IconUri      = 'https://imsreleases.blob.core.windows.net/universal/logo.png'
    
            # ReleaseNotes of this module
            ReleaseNotes = 'https://docs.ironmansoftware.com/changelog'
    
            # Prerelease = "beta3"
    
        } # End of PSData hashtable
    
    } # End of PrivateData hashtable
    
    # HelpInfo URI of this module
    # HelpInfoURI = ''
    
    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
    
}
